//
// Created by HyungWoo Lee on 2022/11/08.
//

#ifndef ROOTING_SCANNER_SRC_MAIN_CPP_SCANNER_SCANNERTYPE_H_
#define ROOTING_SCANNER_SRC_MAIN_CPP_SCANNER_SCANNERTYPE_H_

enum class eSCANNER_TYPE : int {
  eSCANNER_TYPE_START = 0,
    ePACKAGES = 0,
    eBINARY = 1,
    ePERMISSION = 2,
    eWHICH = 3,
    ePROP = 4,
  eSCANNER_TYPE_END = 4
};

#endif //ROOTING_SCANNER_SRC_MAIN_CPP_SCANNER_SCANNERTYPE_H_
